add_newline = false

format = '''╭──\([$username@](bold cyan)[$hostname](bold blue)\)-\[$directory(\]-\[$git_branch$git_status$git_metrics)\]
╰─[$character](bold red) '''

right_format = '$cmd_duration$status'

[character]
success_symbol = "[λ](bold cyan)"
error_symbol = "[λ](bold red)"

[custom.bold]
command = '''
printf "\\033[1m"
'''
when = true
unsafe_no_escape = true
format = "$output"

[line_break]
disabled = false

[username]
format = '$user'
disabled = false
show_always = true

[nix_shell]
symbol = '❄️'
format = '[$symbol $name](bold cyan)'

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)$hostname'
trim_at = '.companyname.com'
disabled = false

[directory]
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = true
style = 'bold white'
format = '[$path]($style)[$read_only]($read_only_style)'

[cmd_duration]
min_time = 1_000
style = "bold dimmed yellow"
format = '◷[$duration]($style) '

[git_branch]
format = "[$symbol$branch(:$remote_branch)](bold yellow)"

[git_status]
format ="([ $all_status$ahead_behind](bold bright-blue))"

[git_metrics]
disabled = false
format = "( | [+$added]($added_style) )([-$deleted]($deleted_style))"

[shell]
fish_indicator =       '󰈺'
powershell_indicator = '_'
bash_indicator =      '\$'
zsh_indicator =        'λ'
unknown_indicator =    '?'
disabled = false
format = '[$indicator](bold)'

[status]
disabled = false

