#!/usr/bin/env zsh

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find /mnt/Books/ -mindepth 1 -maxdepth 3 -type f | fzf --delimiter / --with-nth=4..)
fi

if [[ -z $selected ]]; then
    exit 0
fi

extension="${selected##*.}"

if [[ $extension == "pdf" ]]; then
    okular $selected
elif [[ $extension == "epub" ]]; then
    foliate $selected
else
    echo "File type is currently not supported"
    exit 1
fi
