#!/usr/bin/bash

if [[ $# -eq 0 || $# -gt 3 ]]; then
    echo "Usage:"
    echo -e "\tcompl <file.asm>"
    echo -e "\tcompl <file.asm> <binary>"
    echo -e "\tcompl <file.asm> <obj.o> <binary>"
    exit 1
fi

FILE=$1

if [[ $FILE != *.asm ]]; then
    FILE+=".asm"
fi

if [[ ! -f $FILE  ]]; then
    echo "File does not exist"
    exit 2
fi

if [[ $# -eq 1 ]]; then
    NAME=$(basename $1 .asm)
    OBJ="$NAME.o"
elif [[ $# -eq 2 ]]; then
    NAME=$2
    OBJ="$NAME.o"
elif [[ $# -eq 3 ]]; then
    NAME=$3
    [[ $2 == *.o ]] && OBJ=$2 || OBJ=$2.o
fi

nasm -f elf32 -F dwarf -o $OBJ $FILE && \
ld -m elf_i386 -s -o $NAME $OBJ

./$NAME
