#!/usr/bin/env zsh

selected=$(fd --max-depth 1 --type d . "$HOME/Videos/[FreeTutorials.Eu] [UDEMY] Design Patterns in Modern C++ [FTU]/" | fzf --delimiter / --with-nth=6.. --preview 'eza --long --tree --level=2 --tree --ignore-glob "*.srt|*.txt" {}' | sed 's/\/$//')

if [[ -z $selected ]]; then
    exit 0
fi

selected_vid=$(fd --max-depth 1 --type f -E '*.srt' . "$selected" | fzf --delimiter / --with-nth=7.. --preview 'eza --long --tree --level=2 {}' | sed 's/\/$//')

mpv $selected_vid
