#!/usr/bin/env zsh

# Define the project and output paths
project_path="/home/adrian/dev/DSA-LAB/src/"
output_path="/home/adrian/dev/DSA-LAB/output"

# Create the output directory if it doesn't exist
mkdir -p "${output_path}"

# Change the current directory to the project path
cd "${project_path}"

# Get the current git branch name
git_branch=$(git rev-parse --abbrev-ref HEAD)

# Copy main.cpp to the output directory with the git branch name
cp main.cpp "${output_path}/${git_branch}.cpp"

# Take a full screenshot and save it to the output directory with the git branch name
flameshot full -p "${output_path}/${git_branch}-screenshot"

