#!/usr/bin/zsh

if [[ $# -eq 0 ]]; then
    echo "Usage: tmux-dir <operation> <dir>"
    exit
fi

if [[ $1 != "add" ]] &&  [[ $1 != "remove" ]]; then
    echo "Operation must be either \"add\" or \"remove\""
    exit
fi

dir_list=$HOME/.tmux-dir
dir=$(pwd)

if [[ $1 = "add" ]]; then
    if ! grep -Fxq "$dir" $dir_list; then
        echo $dir >> $HOME/.tmux-dir
    else
        echo "Directory already exists in the list."
    fi
else
    sed -i "\|^$dir$|d" "$dir_list"
fi
