#!/usr/bin/env zsh

dir=$(fd --max-depth 1 --type d -E '{build,src,.cache,.git,.github}' . "$HOME/dev")
dir+="\n"$(cat "$HOME/.tmux-dir")
selected=$(echo $dir | fzf --delimiter / --with-nth=4.. --preview 'eza --long --tree --level=2 {}' | sed 's/\/$//')

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -ds $selected_name -c $selected -n "Source"
    tmux attach-session -t $selected_name
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected -n "Source"
fi

[[ -z $TMUX ]] && tmux attach-session -t $selected_name || tmux switch-client -t $selected_name
